// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shorter.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type URL struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *URL) Reset()         { *m = URL{} }
func (m *URL) String() string { return proto.CompactTextString(m) }
func (*URL) ProtoMessage()    {}
func (*URL) Descriptor() ([]byte, []int) {
	return fileDescriptor_shorter_55268af45bc6a522, []int{0}
}
func (m *URL) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_URL.Unmarshal(m, b)
}
func (m *URL) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_URL.Marshal(b, m, deterministic)
}
func (dst *URL) XXX_Merge(src proto.Message) {
	xxx_messageInfo_URL.Merge(dst, src)
}
func (m *URL) XXX_Size() int {
	return xxx_messageInfo_URL.Size(m)
}
func (m *URL) XXX_DiscardUnknown() {
	xxx_messageInfo_URL.DiscardUnknown(m)
}

var xxx_messageInfo_URL proto.InternalMessageInfo

func (m *URL) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func init() {
	proto.RegisterType((*URL)(nil), "pb.URL")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ShorterClient is the client API for Shorter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShorterClient interface {
	Shorten(ctx context.Context, in *URL, opts ...grpc.CallOption) (*URL, error)
}

type shorterClient struct {
	cc *grpc.ClientConn
}

func NewShorterClient(cc *grpc.ClientConn) ShorterClient {
	return &shorterClient{cc}
}

func (c *shorterClient) Shorten(ctx context.Context, in *URL, opts ...grpc.CallOption) (*URL, error) {
	out := new(URL)
	err := c.cc.Invoke(ctx, "/pb.Shorter/Shorten", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShorterServer is the server API for Shorter service.
type ShorterServer interface {
	Shorten(context.Context, *URL) (*URL, error)
}

func RegisterShorterServer(s *grpc.Server, srv ShorterServer) {
	s.RegisterService(&_Shorter_serviceDesc, srv)
}

func _Shorter_Shorten_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(URL)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShorterServer).Shorten(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Shorter/Shorten",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShorterServer).Shorten(ctx, req.(*URL))
	}
	return interceptor(ctx, in, info, handler)
}

var _Shorter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Shorter",
	HandlerType: (*ShorterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Shorten",
			Handler:    _Shorter_Shorten_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shorter.proto",
}

func init() { proto.RegisterFile("shorter.proto", fileDescriptor_shorter_55268af45bc6a522) }

var fileDescriptor_shorter_55268af45bc6a522 = []byte{
	// 95 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0xce, 0xc8, 0x2f,
	0x2a, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x92, 0xe4,
	0x62, 0x0e, 0x0d, 0xf2, 0x11, 0x12, 0xe2, 0x62, 0x49, 0x4c, 0x49, 0x29, 0x92, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x8d, 0xd4, 0xb8, 0xd8, 0x83, 0x21, 0xea, 0x85, 0xa4, 0x61, 0xcc,
	0x3c, 0x21, 0x76, 0xbd, 0x82, 0x24, 0xbd, 0xd0, 0x20, 0x1f, 0x29, 0x18, 0x23, 0x89, 0x0d, 0x6c,
	0x9a, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xf8, 0xe2, 0x9c, 0x2e, 0x5e, 0x00, 0x00, 0x00,
}
