// @flow
// Automatically generated by Jenny. DO NOT EDIT!
import matchstick from 'matchstick'
import fetch from 'cross-fetch';
import url from 'url';


type URL = {
    Addr?: string,
}


export default class ShorterClient {
  constructor(baseurl: string) {
    this.baseURL=baseurl
   }
  baseURL = ""

  async Shorten( Long: URL,) : Promise<URL>  {
  let pathMaker = matchstick(this.baseURL+`/shorten`, 'template');
  let path = pathMaker.stick({  long: Long, })
  let u = url.parse(path)
  let data : URL  =  await fetch(path);
  return data
}

}
